name: maintenance

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: # Enables on-demand/manual triggering

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  job:
    runs-on: gh-8cpu-runner-mles
    steps:
      - uses: chainguard-actions/actions-checkout@d1f1061cdaee56aa3a3bc3deb86b67b1db772dd6 # v6.0.2
      - run: git submodule update --init --depth=0
      - uses: chainguard-actions/actions-setup-go@a5e8c9530cdd8d86c8c1e22fe4e2d0668896f7c7 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - name: make tflint in tools/magic-modules
        run: |
          git submodule update --remote
          go install golang.org/x/tools/cmd/goimports@latest
          cd tools/magic-modules
          make tflint
        env:
          OUTPUT_PATH: ${{ github.workspace }}/rules/magicmodules
      - uses: step-security/create-pull-request@50c103da2b9ca12cd5bc013fc6931051a5aa872b # v8.1.1
        with:
          commit-message: |
            Update Magic Modules
          title: Update Magic Modules
          delete-branch: true
          body: |
            This is an automated pull request triggered by GitHub Actions. To trigger check runs, close and re-open it.
